[package]
name = "tautology"
version = "0.1.0"
authors = ["Marcus Östling <mpt.ostling@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
